version: "3"
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    volumes:
      - "./sql/script.sql/:/docker-entrypoint-initdb.d/script.sql"

  authorization_server:
    image: "keyist-authorization-server:latest"
    build:
      context: ./authorization_server
    container_name: authorization_server
    depends_on:
      - mysql
    env_file:
      - ./.env
    ports:
      - "8081:8081"

  resource_server:
    image: "keyist-resource-server:latest"
    build:
      context: ./resource_server
    container_name: resource_server
    depends_on:
      - mysql
      - authorization_server
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  client:
    image: "keyist-client:latest"
    build:
      context: ./client
    container_name: client
    depends_on:
      - authorization_server
      - resource_server
    ports:
      - "4200:443"
