logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  error:
    whitelabel:
      enabled: true
  port: 8080
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:resource_server.p12
    key-store-password: rockuS
    key-alias: resource_server

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1200000
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: data-source
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jackson:
    date-format: MMMM dd yyyy / HH:mm
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mail:
    host: ${MAIL_HOST}
    host_address: ${MAIL_HOST_ADDRESS}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    protocol: smtp
  mvc:
    throw-exception-if-no-handler-found: true

security:
  public-pattern: /api/public/**
  auth:
    username: ${OAUTH_USERNAME}
    url: http://localhost:8081/oauth/check_token
    client_id: ${OAUTH_CLIENT_ID}
    client_password: ${OAUTH_CLIENT_PASSWORD}
    connection_timeout: 60
    read_timeout: 60
    whitelist: >
      /,
      /v2/api-docs,
      /swagger-resources,
      /swagger-resources/**,
      /configuration/ui,
      /configuration/security,
      /swagger-ui.html,
      /webjars/**,
      /api/public/**

swagger:
  host:
    address: localhost:8080
    path: /
  api:
    name: Keyist Api Documentation
    version: v1
  contact:
    name: Ant Kaynak
    url: https://www.keyist.tech
    email: antkaynak1@gmail.com
