logging:
  level:
    root: INFO
    com.commerce.oauth: DEBUG # Adicione esta linha para definir o nível de logging para o seu pacote específico
    org:
      hibernate:
        SQL: INFO

server:
  error:
    whitelabel:
      enabled: true
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:authorization_server.p12
    key-store-password: rockuS
    key-alias: authorization_server

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 2
      minimum-idle: 1
      pool-name: data-source
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USERNAME}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
