name: Docker Compose Up

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install haveged
      run: sudo apt-get update && sudo apt-get install -y haveged
    - name: Run the docker compose up
      run: docker compose up
