name: Docker Compose Up

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check out Git repository"
      uses: actions/checkout@v4
    - name: Run the docker compose up
      run: docker compose up --build -d
    - name: "Run the linter"
      run: |
        cd client
        npm run lint
