name: Docker Compose Up

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Run Tests on Resource Server
        run: |
          cd ./resource_server
          mvn test

      - name: Build Resource Server Package
        run: |
          cd ./resource_server
          mvn package

      # - name: Run the docker compose up
      #   run: docker compose up --build -d

      # - name: "Run Backend tests"
      #   run: docker compose exec resource_server mvn test

      - name: "Run the linter"
        run: |
          cd ..
          cd client
          npm run lint
