name: Run tests only
on:
  push:
    branches: ["feature/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v4

      - name: Install Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: "10"

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests on Resource Server
        run: |
          cd ./resource_server
          mvn test

      - name: Run Tests on Authorization Server
        run: |
          cd ./authorization_server
          mvn test

      - name: Run npm install on Client Application
        run: |
          cd ./client
          npm i

      - name: Install Chrome for npm run test (Karma)
        uses: browser-actions/setup-chrome@v1

      - name: Run Tests on Client Application
        run: |
          cd ./client
          npm run test

      - name: Build Client Application Package
        run: |
          cd ./client
          npm run build
